name: ROS2 Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - linter: copyright
            arguments: '--exclude doc/conf.py'
          - linter: lint_cmake
            arguments: ''
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: rolling
          linter: ${{ matrix.env.linter }}
          arguments: ${{ matrix.env.arguments }}
          package-name:
            ur_description
