name: Jazzy Binary Build Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy
  schedule:
    - cron: '53 5 * * *'

jobs:
  jazzy_binary_testing:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: jazzy
      ros_repo: testing
      ref_for_scheduled_build: jazzy
