name: Kilted Binary Build Main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling
  schedule:
    - cron: '53 5 * * *'

jobs:
  kilted_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: kilted
      ros_repo: main
      ref_for_scheduled_build: rolling
