name: Prerelease
on:
  push:
    branches:
      - ros2
    tags:
      - '**'
jobs:
  prerelease:
    name: prerelease build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, kilted, rolling]
        ROS_REPO: [main]
        PRERELEASE: [true]
    env:
      BASEDIR: ${{ github.workspace }}/.work
    steps:
      - uses: actions/checkout@v4
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
          PRERELEASE: ${{ matrix.PRERELEASE }}
