name: Rolling Binary Build Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - rolling
      - ros2
  push:
    branches:
      - rolling
  schedule:
    - cron: '53 5 * * *'

jobs:
  rolling_binary_main:
    uses: ./.github/workflows/reusable_ici.yml
    with:
      ros_distro: rolling
      ros_repo: testing
      ref_for_scheduled_build: rolling
